[package]
name = "market-resonance"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
market-sim = { path = "../../crates/market-sim" }
resonance-audio = { path = "../../crates/resonance-audio" }
anyhow = { workspace = true }
tui-shared = { path = "../../crates/tui-shared" }
crossbeam-channel = "0.5"
cpal = "0.15"
macroquad = "0.4"
