[package]
name = "neuro-market"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm.workspace = true
ratatui.workspace = true
anyhow.workspace = true
rand.workspace = true
neuro-sim = { path = "../../crates/neuro-sim" }
market-sim = { path = "../../crates/market-sim" }
tui-shared = { path = "../../crates/tui-shared" }
