[package]
name = "chron-diffusion"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
crossterm = { workspace = true }
ratatui = { workspace = true }
tui-shared = { workspace = true }
chrono = "0.4"
git2 = "0.18"
gray-scott = { path = "../../crates/gray-scott" }
chrontext = { path = "../chrontext" }
