[package]
name = "chrontext"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
crossterm = { workspace = true }
ratatui = { workspace = true }
git2 = { workspace = true }
chrono = "0.4"

[lib]
name = "chrontext"
path = "src/lib.rs"

[[bin]]
name = "chrontext"
path = "src/main.rs"
