use anyhow::Result;
use hound;

pub struct ScannedSynth {
    samples: Vec<f32>,
    spec: hound::WavSpec,
}

impl ScannedSynth {
    pub fn new() -> Self {
        Self {
            samples: Vec::new(),
            spec: hound::WavSpec {
                channels: 1,
                sample_rate: 44100,
                bits_per_sample: 16,
                sample_format: hound::SampleFormat::Int,
            },
        }
    }

    /// Appends a chunk of audio generated by scanning the provided waveform (grid row).
    /// `waveform`: The slice of f32 from the simulation (e.g. 100 samples).
    /// `duration_secs`: How long this chunk should last (e.g. 1.0/60.0).
    /// `frequency_hz`: The pitch we want to perceive (how many times we scan the waveform per second).
    pub fn push_frame(&mut self, waveform: &[f32], duration_secs: f32, frequency_hz: f32) {
        let sample_rate = self.spec.sample_rate as f32;
        let num_samples_to_gen = (sample_rate * duration_secs) as usize;

        // Length of one cycle in samples at target frequency
        // e.g. 44100 / 440 = 100 samples per cycle.
        let samples_per_cycle = sample_rate / frequency_hz;

        // We step through the waveform
        // waveform.len() corresponds to one cycle (0..2PI)

        for _ in 0..num_samples_to_gen {
            // Calculate phase (0.0 to 1.0) of the current cycle
            // Total time elapsed for this chunk is not tracked globally here,
            // but we can just loop locally.
            // Wait, to ensure continuity, we should track phase.
            // But for "Weird Tech" glitchy sound is acceptable.
            // Let's try to be smooth. We need state.
            // But `push_frame` implies discrete updates.
            // Let's assume we start phase at 0 for every frame? No, that clicks.
            // Let's just create a "texture" sound.

            // Simple approach: Resample `waveform` to fit `samples_per_cycle` and repeat.
            // `global_sample_index` would be needed for perfect phase.
            // Let's add `phase` to struct if we want smooth.

            // Re-think: "Scanned Synthesis" usually means the update rate of the model is slow (Control Rate),
            // and we read the shape at Audio Rate.
            // We just need to interpolate the waveform at the current phase.

            let phase = (self.samples.len() as f32 % samples_per_cycle) / samples_per_cycle;
            // map phase [0, 1] to index [0, waveform.len()]
            let idx_f = phase * (waveform.len() as f32);
            let idx = idx_f as usize % waveform.len();
            let next_idx = (idx + 1) % waveform.len();
            let frac = idx_f - idx as f32;

            // Linear interpolation
            let sample = waveform[idx] * (1.0 - frac) + waveform[next_idx] * frac;

            // Soft clip / master volume
            let val = sample.clamp(-1.0, 1.0) * 0.5;

            self.samples.push(val);
        }
    }

    pub fn save(&self, path: &str) -> Result<()> {
        let mut writer = hound::WavWriter::create(path, self.spec)?;
        let amplitude = i16::MAX as f32;

        for &sample in &self.samples {
            writer.write_sample((sample * amplitude) as i16)?;
        }

        writer.finalize()?;
        Ok(())
    }
}
