import os
import subprocess

def is_hybrid(crate_name):
    # Very rudimentary check if a crate is a hybrid by checking if its name contains '-' and isn't a core library.
    # We can also check GUESTBOOK.md to see if it was generated by Splice Surgeon.
    with open('GUESTBOOK.md', 'r') as f:
        guestbook = f.read()
    if crate_name in guestbook and ('NEW HYBRID' in guestbook.split(crate_name)[0][-200:] or 'The Splice Surgeon' in guestbook.split(crate_name)[1][:200]):
         return True

    with open('MUTATIONS.md', 'r') as f:
        if f"### {crate_name}" in f.read():
             return True
    return False

missing = []
for d in os.listdir('experiments'):
    if not is_hybrid(d):
         continue

    with open('MUTATIONS.md', 'r') as f:
        mutations = f.read()

    if f"### {d}" not in mutations:
         missing.append(d)

print("Missing in MUTATIONS:", missing)

hybrids = []
with open('MUTATIONS.md', 'r') as f:
    for line in f:
         if line.startswith("### "):
              hybrids.append(line.strip().replace("### ", ""))

print("Hybrids missing evaluation:")
for hybrid in hybrids:
    with open('MUTATIONS.md', 'r') as f:
         content = f.read()
         hybrid_block = content.split(f"### {hybrid}")[1].split("### ")[0]
         if "- **Evaluation**:" not in hybrid_block:
              print(hybrid)
