[package]
name = "git-hologram"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
crossterm.workspace = true
ratatui.workspace = true
rand.workspace = true
tui-shared.workspace = true
ferrous-core.workspace = true
platter.workspace = true
locus.workspace = true
git2.workspace = true
num-complex = "0.4"
rustfft = "6.2"