[package]
name = "quipu-chimera"
version = "0.1.0"
edition = "2021"

[dependencies]
chimera-lang = { workspace = true }
ratatui = { workspace = true }
crossterm = { workspace = true }
anyhow = { workspace = true }
rand = { workspace = true }
crossbeam-channel = "0.5"
tui-shared = { workspace = true }
quipu = { workspace = true, optional = true }

[features]
default = []
audio = ["dep:quipu", "quipu/audio"]
