[package]
name = "flock-platter"
version = "0.1.0"
edition = "2021"

[dependencies]
flocking = { path = "../../crates/flocking" }
platter = { path = "../../crates/platter" }
locus = { path = "../../crates/locus" }
tui-shared = { path = "../../crates/tui-shared" }
anyhow = { workspace = true }
crossterm = { workspace = true }
rand = { workspace = true }
ratatui = { workspace = true }
