[package]
name = "flock-platter"
version = "0.1.0"
edition = "2021"

[dependencies]
flocking = { path = "../../crates/flocking" }
locus = { path = "../../crates/locus" }
platter = { path = "../../crates/platter" }
tui-shared = { path = "../../crates/tui-shared" }
ratatui.workspace = true
crossterm.workspace = true
anyhow.workspace = true
rand = "0.8"
