[package]
name = "hanging-gardens"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
crossterm = { workspace = true }
ratatui = { workspace = true }
rand = { workspace = true }
chrono = "0.4"
tui-shared = { path = "../../crates/tui-shared" }
git-associates = { path = "../../crates/git-associates" }
