[package]
name = "symphonic-terrain"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = "0.4"
noise = "0.9"
anyhow = "1.0"
rand = "0.8"
ab_glyph = "0.2.32"
glyph_brush_layout = "0.2.4"

[dependencies.cpal]
version = "0.15"
optional = true

[features]
default = []
audio = ["cpal"]

[dev-dependencies]
proptest = "1.4.0"
