[package]
name = "bismuth-fs"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.14", default-features = false, features = [
    "bevy_asset",
    "bevy_winit",
    "bevy_core_pipeline",
    "bevy_pbr",
    "bevy_render",
    "bevy_sprite",
    "bevy_text",
    "bevy_ui",
    "multi_threaded",
    "png",
    "x11",
    "tonemapping_luts",
    "default_font"
] }
walkdir = "2"
rand = { workspace = true }
anyhow = { workspace = true }
