[package]
name = "heap-arena"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
crossterm = { workspace = true }
ratatui = { workspace = true }
rand = { workspace = true }
tui-shared = { workspace = true }
syn = { version = "2.0", features = ["full", "visit", "extra-traits"] }
walkdir = "2.3"
quote = "1.0"
proc-macro2 = { version = "1.0", features = ["span-locations"] }

[dev-dependencies]
tempfile = "3.26.0"
