[package]
name = "synesthesia-diffusion"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.14", default-features = false, features = [
    "animation",
    "bevy_asset",
    "bevy_core_pipeline",
    "bevy_render",
    "bevy_sprite",
    "bevy_text",
    "bevy_ui",
    "bevy_winit",
    "x11",
    "tonemapping_luts",
    "default_font",
    "png",
    "hdr",
] }
cpal = { version = "0.15", optional = true }
spectrum-analyzer = "1.5"
rand = "0.8"
bytemuck = { version = "1.16", features = ["derive"] }

[features]
default = []
audio = ["dep:cpal"]
