[package]
name = "cargo-jenga"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
crossterm = { workspace = true }
ratatui = { workspace = true }
tui-shared = { path = "../../crates/tui-shared" }
rapier2d = "0.21.0"
nalgebra = "0.33"
cargo_metadata = "0.18"
rand = { workspace = true }
