[package]
name = "hyper-acoustics"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = "0.4.15"
sysinfo = "0.30"
hyper-system = { workspace = true }
crossbeam-channel = "0.5"
anyhow = "1.0"
rand = "0.8"

[dependencies.cpal]
version = "0.15"
optional = true

[features]
default = []
audio = ["dep:cpal"]
