[package]
name = "synaptic-pachinko"
version = "0.1.0"
edition = "2021"

[features]
default = ["audio"]
audio = ["dep:cpal"]

[dependencies]
ratatui = { workspace = true }
crossterm = { workspace = true }
anyhow = { workspace = true }
rand = { workspace = true }
tui-shared = { workspace = true }
cpal = { version = "0.15", optional = true }
ringbuf = "0.3"
crossbeam-channel = "0.5"
synaptic-physics = { workspace = true }
