[package]
name = "quipu-symphony"
version = "0.1.0"
edition = "2021"

[dependencies]
quipu = { workspace = true }
anyhow = { workspace = true }
crossbeam-channel = "0.5"
crossterm = { workspace = true }
parking_lot = "0.12"
rand = { workspace = true }
ratatui = { workspace = true }
tui-shared = { workspace = true }

[features]
default = []
audio = ["quipu/audio"]
