[package]
name = "miller-market"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
miller-lattice = { path = "../../crates/miller-lattice" }
market-sim = { path = "../../crates/market-sim" }
tui-shared = { path = "../../crates/tui-shared" }
anyhow = { workspace = true }
ratatui = { workspace = true }
crossterm = { workspace = true }
cgmath = "0.18"
