[package]
name = "code-catchment"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.14", default-features = false, features = [
    "bevy_winit",
    "bevy_pbr",
    "bevy_render",
    "bevy_core_pipeline",
    "bevy_sprite",
    "bevy_text",
    "bevy_ui",
    "bevy_gizmos",
    "multi_threaded",
    "x11",
    "tonemapping_luts",
    "default_font",
    "png",
] }
git2 = { workspace = true }
rand = { workspace = true }
noise = "0.9"
