[package]
name = "git-harmony"
version = "0.2.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
crossterm = { workspace = true }
ratatui = { workspace = true }
git-associates = { path = "../../crates/git-associates" }
cpal = { version = "0.15", optional = true }
crossbeam-channel = "0.5"
resonance-audio = { path = "../../crates/resonance-audio" }

[features]
default = []
audio = ["cpal"]
