[package]
name = "harmonic-chimera"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
ratatui = "0.30.0"
rapier2d = "0.27.0"
nalgebra = "0.33.2"
rand = "0.8.5"
anyhow = "1.0.101"

[dependencies.harmonic-engine]
path = "../harmonic-engine"

[dependencies.chimera-lang]
path = "../chimera-lang"
