[package]
name = "ferrous-legion"
version = "0.1.0"
edition = "2021"

[dependencies]
platter = { workspace = true }
ratatui = { workspace = true }
crossterm = { workspace = true }
rand = { workspace = true }
anyhow = { workspace = true }
walkdir = "2.3"
regex = "1.10"
num-bigint = { version = "0.4", features = ["rand"] }
num-traits = "0.2"
num-integer = "0.1"
