[package]
name = "phonetic-decay"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
crossterm.workspace = true
prettyplease = "0.2"
proc-macro2 = "1.0"
quote = "1.0"
rand.workspace = true
ratatui.workspace = true
syn = { version = "2.0", features = ["full", "visit-mut"] }
unicode-segmentation = "1.10"
