[package]
name = "myco-fluid"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
crossterm = { workspace = true }
ratatui = { workspace = true }
rand = { workspace = true }
tui-shared = { workspace = true }
locus = { workspace = true }
ferrous-core = { workspace = true }
rayon = "1.11.0"
