[package]
name = "neuro-git"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = { workspace = true }
ratatui = { workspace = true }
neuro-sim = { path = "../../crates/neuro-sim" }
git-associates = { path = "../../crates/git-associates" }
tui-shared = { path = "../../crates/tui-shared" }
