[package]
name = "chimera-resonance"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
crossterm = { workspace = true }
ratatui = { workspace = true }
crossbeam-channel = "0.5"
tui-shared = { workspace = true }
chimera-lang = { path = "../chimera-lang", features = ["nova"] }
rand = "0.8"

[dependencies.cpal]
version = "0.15"
optional = true

[features]
default = []
audio = ["cpal"]
