[package]
name = "git-phasing"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
crossterm.workspace = true
parking_lot = "0.12.5"
ratatui.workspace = true
tui-shared = { version = "0.1.0", path = "../../crates/tui-shared" }

[dependencies.cpal]
version = "0.17.1"
optional = true

[features]
default = []
audio = ["cpal"]
