[package]
name = "git-flock"
version = "0.1.0"
edition = "2021"

[dependencies]
flocking = { workspace = true }
locus = { workspace = true }
anyhow = { workspace = true }
crossterm = { workspace = true }
rand = { workspace = true }
ratatui = { workspace = true }
tui-shared = { workspace = true }
git2 = "0.21.0"
chrono = "0.4"
