[package]
name = "chimera-maat"
version = "0.1.0"
edition = "2021"

[dependencies]
chimera-lang = { path = "../chimera-lang", features = ["nova"] }
maat-engine = { path = "../maat-engine" }
ratatui = { workspace = true }
crossterm = { workspace = true }
anyhow = { workspace = true }
rand = { workspace = true }
num-bigint = { version = "0.4", features = ["rand"] }
num-rational = { version = "0.4", features = ["num-bigint"] }
num-traits = "0.2"
