[package]
name = "tectonic-flock"
version = "0.1.0"
edition = "2021"

[dependencies]
locus = { workspace = true }
flocking = { workspace = true }
tui-shared = { workspace = true }
ratatui = { workspace = true }
crossterm = { workspace = true }
anyhow = { workspace = true }
rand = { workspace = true }
chrono = "0.4"
