[package]
name = "gray-flock"
version = "0.1.0"
edition = "2024"

[dependencies]
locus = { workspace = true }
gray-scott = { workspace = true }
tui-shared = { workspace = true }
ratatui = { workspace = true }
crossterm = { workspace = true }
anyhow = { workspace = true }
rand = { workspace = true }
