[package]
name = "chimera-lang"
version = "0.1.0"
edition = "2021"

[features]
default = ["nova", "oracle", "elektra"]
nova = ["oracle"]
cortex = []
biophysics = []
oracle = []
silicon = []
elektra = []
git = []
phylogeny = []
hive = []
resonance = ["dep:resonance-audio", "dep:crossbeam-channel"]

[dependencies]
regex = "1.10"
locus = { workspace = true, features = ["serde"] }
pest = "2.7"
pest_derive = "2.7"
clap = { version = "4.4", features = ["derive"] }
anyhow = { workspace = true }
ratatui = { workspace = true }
crossterm = { workspace = true }
rand = "0.8"
crossbeam-channel = { version = "0.5", optional = true }
resonance-audio = { workspace = true, optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
strum = "0.26"
strum_macros = "0.26"
poincare-disk = { path = "../../crates/poincare-disk" }
comfy-table = "7.2.2"

[[example]]
name = "story_demo"

[[bin]]
name = "prologue"
path = "src/bin/prologue.rs"
