[package]
name = "clockwork-cpu"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = { workspace = true }
crossterm = { workspace = true }
anyhow = { workspace = true }
rapier2d = "0.21.0"
tui-shared = { path = "../../crates/tui-shared" }
nalgebra = "0.33" # rapier2d 0.21 uses nalgebra 0.33
