[package]
name = "chimera-acoustics"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = "0.4.15"
chimera-lang = { path = "../chimera-lang", features = ["nova"] }
crossbeam-channel = "0.5"
sysinfo = "0.30"
rand = "0.8"
parking_lot = "0.12"
anyhow = "1.0"

[dependencies.cpal]
version = "0.15"
optional = true

[features]
default = []
audio = ["dep:cpal"]
